### ISSUE TITLE
初期装備について

### ISSUE THREAD

**Issue by takeyari** [takeyari/Rust#5]
初期装備は、石剣、弓、矢*45、ダイヤピッケル、石斧、ベークドポテト*16、ガラス*32、アカシア原木*64、TNT(地形破壊無し)*1(TNTは敵を倒すと一つ貰える)。
初期防具は、赤、青色の皮メット、チェーン装備一式。
以上でいかがでしょうか

**Comment by afuafu55** [comment]
いいんじゃね

**Comment by takeyari** [comment]
ダイヤとかをkill報酬でってのも考えてるけどどうかな

**Comment by afuafu55** [comment]
ダイヤは強すぎな気がする

**Comment by takeyari** [comment]
でもダイヤが貰えるマップあったんだよなあ

**Comment by nanostoy** [comment]
アカシアの理由は

**Comment by takeyari** [comment]
ダイヤは鉄と同じように埋めることにした

**Comment by nanostoy** [comment]
アカシア理由ないならめんどくないしオークの原木にしますよ

**Comment by afuafu55** [comment]
逆にオークにする理由もないやろ

**Comment by takeyari** [comment]
橋かけてるのが見えやすいようにアカシアにしてみた

**Comment by takeyari** [comment]
初期装備は、石剣、弓、矢45、ダイヤピッケル、石斧、ベークドポテト16、ガラス32、アカシア原木64、TNT(地形破壊無し)*1(TNTは敵を倒すと一つ貰える)。
初期防具は、赤、青色の皮メット、チェーン装備一式。
以上で決定として閉じます
